services:
  nginx:
    ports:
      - "5000:80"
  api:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ".:/app"
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password